!:=============================================================================
! This file is part of FPL (Fortran Processing Library).

! Copyright (C) 2015 Fernando Martins Pimenta

! FPL is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.

! FPL is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.

! You should have received a copy of the GNU General Public License
! along with FPL.  If not, see <http://www.gnu.org/licenses/>.

!:=============================================================================
! About Author:
! Fernando Martins Pimenta
!  Student of Surveying and Cartographic Engineering
!  Federal University of Viçosa - Brazil

!  Bachelor of Biosystems Engineer
!  Federal University of São João del-Rei - Brazil

!  Research Group on Atmosphere-Biosphere Interaction
!  Federal University of Viçosa
!  Data: August 09, 2015

!Contacts: fernando.m.pimenta@gmail.com, fernando.m.pimenta@ufv.br
!:=============================================================================

interface check
  module procedure checkerror, checktype, checkatt
end interface check

interface griddims
  module procedure griddims2d_byte_llf, &
                griddims2d_short_llf, &
                griddims2d_int_llf, &
                griddims2d_float_llf, &
                griddims2d_double_llf, &
                griddims2d_byte_lld, &
                griddims2d_short_lld, &
                griddims2d_int_lld, &
                griddims2d_float_lld, &
                griddims2d_double_lld, &
                griddims3d_byte_llf_ti, &
                griddims3d_short_llf_ti, &
                griddims3d_int_llf_ti, &
                griddims3d_float_llf_ti, &
                griddims3d_double_llf_ti, &
                griddims3d_byte_lld_ti, &
                griddims3d_short_lld_ti, &
                griddims3d_int_lld_ti, &
                griddims3d_float_lld_ti, &
                griddims3d_double_lld_ti, &
                griddims3d_byte_llf_tf, &
                griddims3d_short_llf_tf, &
                griddims3d_int_llf_tf, &
                griddims3d_float_llf_tf, &
                griddims3d_double_llf_tf, &
                griddims3d_byte_lld_tf, &
                griddims3d_short_lld_tf, &
                griddims3d_int_lld_tf, &
                griddims3d_float_lld_tf, &
                griddims3d_double_lld_tf, &
                griddims3d_byte_llf_td, &
                griddims3d_short_llf_td, &
                griddims3d_int_llf_td, &
                griddims3d_float_llf_td, &
                griddims3d_double_llf_td, &
                griddims3d_byte_lld_td, &
                griddims3d_short_lld_td, &
                griddims3d_int_lld_td, &
                griddims3d_float_lld_td, &
                griddims3d_double_lld_td, &
                griddims4d_byte_llf_ti_li, &
                griddims4d_short_llf_ti_li, &
                griddims4d_int_llf_ti_li, &
                griddims4d_float_llf_ti_li, &
                griddims4d_double_llf_ti_li, &
                griddims4d_byte_lld_ti_li, &
                griddims4d_short_lld_ti_li, &
                griddims4d_int_lld_ti_li, &
                griddims4d_float_lld_ti_li, &
                griddims4d_double_lld_ti_li, &
                griddims4d_byte_llf_tf_li, &
                griddims4d_short_llf_tf_li, &
                griddims4d_int_llf_tf_li, &
                griddims4d_float_llf_tf_li, &
                griddims4d_double_llf_tf_li, &
                griddims4d_byte_lld_tf_li, &
                griddims4d_short_lld_tf_li, &
                griddims4d_int_lld_tf_li, &
                griddims4d_float_lld_tf_li, &
                griddims4d_double_lld_tf_li, &
                griddims4d_byte_llf_td_li, &
                griddims4d_short_llf_td_li, &
                griddims4d_int_llf_td_li, &
                griddims4d_float_llf_td_li, &
                griddims4d_double_llf_td_li, &
                griddims4d_byte_lld_td_li, &
                griddims4d_short_lld_td_li, &
                griddims4d_int_lld_td_li, &
                griddims4d_float_lld_td_li, &
                griddims4d_double_lld_td_li, &
                griddims4d_byte_llf_ti_lf, &
                griddims4d_short_llf_ti_lf, &
                griddims4d_int_llf_ti_lf, &
                griddims4d_float_llf_ti_lf, &
                griddims4d_double_llf_ti_lf, &
                griddims4d_byte_lld_ti_lf, &
                griddims4d_short_lld_ti_lf, &
                griddims4d_int_lld_ti_lf, &
                griddims4d_float_lld_ti_lf, &
                griddims4d_double_lld_ti_lf, &
                griddims4d_byte_llf_tf_lf, &
                griddims4d_short_llf_tf_lf, &
                griddims4d_int_llf_tf_lf, &
                griddims4d_float_llf_tf_lf, &
                griddims4d_double_llf_tf_lf, &
                griddims4d_byte_lld_tf_lf, &
                griddims4d_short_lld_tf_lf, &
                griddims4d_int_lld_tf_lf, &
                griddims4d_float_lld_tf_lf, &
                griddims4d_double_lld_tf_lf, &
                griddims4d_byte_llf_td_lf, &
                griddims4d_short_llf_td_lf, &
                griddims4d_int_llf_td_lf, &
                griddims4d_float_llf_td_lf, &
                griddims4d_double_llf_td_lf, &
                griddims4d_byte_lld_td_lf, &
                griddims4d_short_lld_td_lf, &
                griddims4d_int_lld_td_lf, &
                griddims4d_float_lld_td_lf, &
                griddims4d_double_lld_td_lf
end interface griddims

interface readgrid
  module procedure readgrid2d_byte_llf, &
                readgrid2d_short_llf, &
                readgrid2d_int_llf, &
                readgrid2d_float_llf, &
                readgrid2d_double_llf, &
                readgrid2d_byte_lld, &
                readgrid2d_short_lld, &
                readgrid2d_int_lld, &
                readgrid2d_float_lld, &
                readgrid2d_double_lld, &
                readgrid3d_byte_llf_ti, &
                readgrid3d_short_llf_ti, &
                readgrid3d_int_llf_ti, &
                readgrid3d_float_llf_ti, &
                readgrid3d_double_llf_ti, &
                readgrid3d_byte_lld_ti, &
                readgrid3d_short_lld_ti, &
                readgrid3d_int_lld_ti, &
                readgrid3d_float_lld_ti, &
                readgrid3d_double_lld_ti, &
                readgrid3d_byte_llf_tf, &
                readgrid3d_short_llf_tf, &
                readgrid3d_int_llf_tf, &
                readgrid3d_float_llf_tf, &
                readgrid3d_double_llf_tf, &
                readgrid3d_byte_lld_tf, &
                readgrid3d_short_lld_tf, &
                readgrid3d_int_lld_tf, &
                readgrid3d_float_lld_tf, &
                readgrid3d_double_lld_tf, &
                readgrid3d_byte_llf_td, &
                readgrid3d_short_llf_td, &
                readgrid3d_int_llf_td, &
                readgrid3d_float_llf_td, &
                readgrid3d_double_llf_td, &
                readgrid3d_byte_lld_td, &
                readgrid3d_short_lld_td, &
                readgrid3d_int_lld_td, &
                readgrid3d_float_lld_td, &
                readgrid3d_double_lld_td, &
                readgrid4d_byte_llf_ti_li, &
                readgrid4d_short_llf_ti_li, &
                readgrid4d_int_llf_ti_li, &
                readgrid4d_float_llf_ti_li, &
                readgrid4d_double_llf_ti_li, &
                readgrid4d_byte_lld_ti_li, &
                readgrid4d_short_lld_ti_li, &
                readgrid4d_int_lld_ti_li, &
                readgrid4d_float_lld_ti_li, &
                readgrid4d_double_lld_ti_li, &
                readgrid4d_byte_llf_tf_li, &
                readgrid4d_short_llf_tf_li, &
                readgrid4d_int_llf_tf_li, &
                readgrid4d_float_llf_tf_li, &
                readgrid4d_double_llf_tf_li, &
                readgrid4d_byte_lld_tf_li, &
                readgrid4d_short_lld_tf_li, &
                readgrid4d_int_lld_tf_li, &
                readgrid4d_float_lld_tf_li, &
                readgrid4d_double_lld_tf_li, &
                readgrid4d_byte_llf_td_li, &
                readgrid4d_short_llf_td_li, &
                readgrid4d_int_llf_td_li, &
                readgrid4d_float_llf_td_li, &
                readgrid4d_double_llf_td_li, &
                readgrid4d_byte_lld_td_li, &
                readgrid4d_short_lld_td_li, &
                readgrid4d_int_lld_td_li, &
                readgrid4d_float_lld_td_li, &
                readgrid4d_double_lld_td_li, &
                readgrid4d_byte_llf_ti_lf, &
                readgrid4d_short_llf_ti_lf, &
                readgrid4d_int_llf_ti_lf, &
                readgrid4d_float_llf_ti_lf, &
                readgrid4d_double_llf_ti_lf, &
                readgrid4d_byte_lld_ti_lf, &
                readgrid4d_short_lld_ti_lf, &
                readgrid4d_int_lld_ti_lf, &
                readgrid4d_float_lld_ti_lf, &
                readgrid4d_double_lld_ti_lf, &
                readgrid4d_byte_llf_tf_lf, &
                readgrid4d_short_llf_tf_lf, &
                readgrid4d_int_llf_tf_lf, &
                readgrid4d_float_llf_tf_lf, &
                readgrid4d_double_llf_tf_lf, &
                readgrid4d_byte_lld_tf_lf, &
                readgrid4d_short_lld_tf_lf, &
                readgrid4d_int_lld_tf_lf, &
                readgrid4d_float_lld_tf_lf, &
                readgrid4d_double_lld_tf_lf, &
                readgrid4d_byte_llf_td_lf, &
                readgrid4d_short_llf_td_lf, &
                readgrid4d_int_llf_td_lf, &
                readgrid4d_float_llf_td_lf, &
                readgrid4d_double_llf_td_lf, &
                readgrid4d_byte_lld_td_lf, &
                readgrid4d_short_lld_td_lf, &
                readgrid4d_int_lld_td_lf, &
                readgrid4d_float_lld_td_lf, &
                readgrid4d_double_lld_td_lf
end interface readgrid

interface writegrid
  module procedure writegrid2d_byte_llf, &
                writegrid2d_short_llf, &
                writegrid2d_int_llf, &
                writegrid2d_float_llf, &
                writegrid2d_double_llf, &
                writegrid2d_byte_lld, &
                writegrid2d_short_lld, &
                writegrid2d_int_lld, &
                writegrid2d_float_lld, &
                writegrid2d_double_lld, &
                writegrid3d_byte_llf_ti, &
                writegrid3d_short_llf_ti, &
                writegrid3d_int_llf_ti, &
                writegrid3d_float_llf_ti, &
                writegrid3d_double_llf_ti, &
                writegrid3d_byte_lld_ti, &
                writegrid3d_short_lld_ti, &
                writegrid3d_int_lld_ti, &
                writegrid3d_float_lld_ti, &
                writegrid3d_double_lld_ti, &
                writegrid3d_byte_llf_tf, &
                writegrid3d_short_llf_tf, &
                writegrid3d_int_llf_tf, &
                writegrid3d_float_llf_tf, &
                writegrid3d_double_llf_tf, &
                writegrid3d_byte_lld_tf, &
                writegrid3d_short_lld_tf, &
                writegrid3d_int_lld_tf, &
                writegrid3d_float_lld_tf, &
                writegrid3d_double_lld_tf, &
                writegrid3d_byte_llf_td, &
                writegrid3d_short_llf_td, &
                writegrid3d_int_llf_td, &
                writegrid3d_float_llf_td, &
                writegrid3d_double_llf_td, &
                writegrid3d_byte_lld_td, &
                writegrid3d_short_lld_td, &
                writegrid3d_int_lld_td, &
                writegrid3d_float_lld_td, &
                writegrid3d_double_lld_td, &
                writegrid4d_byte_llf_ti_li, &
                writegrid4d_short_llf_ti_li, &
                writegrid4d_int_llf_ti_li, &
                writegrid4d_float_llf_ti_li, &
                writegrid4d_double_llf_ti_li, &
                writegrid4d_byte_lld_ti_li, &
                writegrid4d_short_lld_ti_li, &
                writegrid4d_int_lld_ti_li, &
                writegrid4d_float_lld_ti_li, &
                writegrid4d_double_lld_ti_li, &
                writegrid4d_byte_llf_tf_li, &
                writegrid4d_short_llf_tf_li, &
                writegrid4d_int_llf_tf_li, &
                writegrid4d_float_llf_tf_li, &
                writegrid4d_double_llf_tf_li, &
                writegrid4d_byte_lld_tf_li, &
                writegrid4d_short_lld_tf_li, &
                writegrid4d_int_lld_tf_li, &
                writegrid4d_float_lld_tf_li, &
                writegrid4d_double_lld_tf_li, &
                writegrid4d_byte_llf_td_li, &
                writegrid4d_short_llf_td_li, &
                writegrid4d_int_llf_td_li, &
                writegrid4d_float_llf_td_li, &
                writegrid4d_double_llf_td_li, &
                writegrid4d_byte_lld_td_li, &
                writegrid4d_short_lld_td_li, &
                writegrid4d_int_lld_td_li, &
                writegrid4d_float_lld_td_li, &
                writegrid4d_double_lld_td_li, &
                writegrid4d_byte_llf_ti_lf, &
                writegrid4d_short_llf_ti_lf, &
                writegrid4d_int_llf_ti_lf, &
                writegrid4d_float_llf_ti_lf, &
                writegrid4d_double_llf_ti_lf, &
                writegrid4d_byte_lld_ti_lf, &
                writegrid4d_short_lld_ti_lf, &
                writegrid4d_int_lld_ti_lf, &
                writegrid4d_float_lld_ti_lf, &
                writegrid4d_double_lld_ti_lf, &
                writegrid4d_byte_llf_tf_lf, &
                writegrid4d_short_llf_tf_lf, &
                writegrid4d_int_llf_tf_lf, &
                writegrid4d_float_llf_tf_lf, &
                writegrid4d_double_llf_tf_lf, &
                writegrid4d_byte_lld_tf_lf, &
                writegrid4d_short_lld_tf_lf, &
                writegrid4d_int_lld_tf_lf, &
                writegrid4d_float_lld_tf_lf, &
                writegrid4d_double_lld_tf_lf, &
                writegrid4d_byte_llf_td_lf, &
                writegrid4d_short_llf_td_lf, &
                writegrid4d_int_llf_td_lf, &
                writegrid4d_float_llf_td_lf, &
                writegrid4d_double_llf_td_lf, &
                writegrid4d_byte_lld_td_lf, &
                writegrid4d_short_lld_td_lf, &
                writegrid4d_int_lld_td_lf, &
                writegrid4d_float_lld_td_lf, &
                writegrid4d_double_lld_td_lf
end interface writegrid

interface setFillValue
  module procedure setfvalue2d_bytebyte_llf, &
                setfvalue2d_byteshort_llf, &
                setfvalue2d_byteint_llf, &
                setfvalue2d_bytefloat_llf, &
                setfvalue2d_bytedouble_llf, &
                setfvalue2d_shortbyte_llf, &
                setfvalue2d_shortshort_llf, &
                setfvalue2d_shortint_llf, &
                setfvalue2d_shortfloat_llf, &
                setfvalue2d_shortdouble_llf, &
                setfvalue2d_intbyte_llf, &
                setfvalue2d_intshort_llf, &
                setfvalue2d_intint_llf, &
                setfvalue2d_intfloat_llf, &
                setfvalue2d_intdouble_llf, &
                setfvalue2d_floatbyte_llf, &
                setfvalue2d_floatshort_llf, &
                setfvalue2d_floatint_llf, &
                setfvalue2d_floatfloat_llf, &
                setfvalue2d_floatdouble_llf, &
                setfvalue2d_doublebyte_llf, &
                setfvalue2d_doubleshort_llf, &
                setfvalue2d_doubleint_llf, &
                setfvalue2d_doublefloat_llf, &
                setfvalue2d_doubledouble_llf, &
                setfvalue2d_bytebyte_lld, &
                setfvalue2d_byteshort_lld, &
                setfvalue2d_byteint_lld, &
                setfvalue2d_bytefloat_lld, &
                setfvalue2d_bytedouble_lld, &
                setfvalue2d_shortbyte_lld, &
                setfvalue2d_shortshort_lld, &
                setfvalue2d_shortint_lld, &
                setfvalue2d_shortfloat_lld, &
                setfvalue2d_shortdouble_lld, &
                setfvalue2d_intbyte_lld, &
                setfvalue2d_intshort_lld, &
                setfvalue2d_intint_lld, &
                setfvalue2d_intfloat_lld, &
                setfvalue2d_intdouble_lld, &
                setfvalue2d_floatbyte_lld, &
                setfvalue2d_floatshort_lld, &
                setfvalue2d_floatint_lld, &
                setfvalue2d_floatfloat_lld, &
                setfvalue2d_floatdouble_lld, &
                setfvalue2d_doublebyte_lld, &
                setfvalue2d_doubleshort_lld, &
                setfvalue2d_doubleint_lld, &
                setfvalue2d_doublefloat_lld, &
                setfvalue2d_doubledouble_lld, &
                setfvalue3d_bytebyte_llf_ti, &
                setfvalue3d_byteshort_llf_ti, &
                setfvalue3d_byteint_llf_ti, &
                setfvalue3d_bytefloat_llf_ti, &
                setfvalue3d_bytedouble_llf_ti, &
                setfvalue3d_shortbyte_llf_ti, &
                setfvalue3d_shortshort_llf_ti, &
                setfvalue3d_shortint_llf_ti, &
                setfvalue3d_shortfloat_llf_ti, &
                setfvalue3d_shortdouble_llf_ti, &
                setfvalue3d_intbyte_llf_ti, &
                setfvalue3d_intshort_llf_ti, &
                setfvalue3d_intint_llf_ti, &
                setfvalue3d_intfloat_llf_ti, &
                setfvalue3d_intdouble_llf_ti, &
                setfvalue3d_floatbyte_llf_ti, &
                setfvalue3d_floatshort_llf_ti, &
                setfvalue3d_floatint_llf_ti, &
                setfvalue3d_floatfloat_llf_ti, &
                setfvalue3d_floatdouble_llf_ti, &
                setfvalue3d_doublebyte_llf_ti, &
                setfvalue3d_doubleshort_llf_ti, &
                setfvalue3d_doubleint_llf_ti, &
                setfvalue3d_doublefloat_llf_ti, &
                setfvalue3d_doubledouble_llf_ti, &
                setfvalue3d_bytebyte_lld_ti, &
                setfvalue3d_byteshort_lld_ti, &
                setfvalue3d_byteint_lld_ti, &
                setfvalue3d_bytefloat_lld_ti, &
                setfvalue3d_bytedouble_lld_ti, &
                setfvalue3d_shortbyte_lld_ti, &
                setfvalue3d_shortshort_lld_ti, &
                setfvalue3d_shortint_lld_ti, &
                setfvalue3d_shortfloat_lld_ti, &
                setfvalue3d_shortdouble_lld_ti, &
                setfvalue3d_intbyte_lld_ti, &
                setfvalue3d_intshort_lld_ti, &
                setfvalue3d_intint_lld_ti, &
                setfvalue3d_intfloat_lld_ti, &
                setfvalue3d_intdouble_lld_ti, &
                setfvalue3d_floatbyte_lld_ti, &
                setfvalue3d_floatshort_lld_ti, &
                setfvalue3d_floatint_lld_ti, &
                setfvalue3d_floatfloat_lld_ti, &
                setfvalue3d_floatdouble_lld_ti, &
                setfvalue3d_doublebyte_lld_ti, &
                setfvalue3d_doubleshort_lld_ti, &
                setfvalue3d_doubleint_lld_ti, &
                setfvalue3d_doublefloat_lld_ti, &
                setfvalue3d_doubledouble_lld_ti, &
                setfvalue3d_bytebyte_llf_tf, &
                setfvalue3d_byteshort_llf_tf, &
                setfvalue3d_byteint_llf_tf, &
                setfvalue3d_bytefloat_llf_tf, &
                setfvalue3d_bytedouble_llf_tf, &
                setfvalue3d_shortbyte_llf_tf, &
                setfvalue3d_shortshort_llf_tf, &
                setfvalue3d_shortint_llf_tf, &
                setfvalue3d_shortfloat_llf_tf, &
                setfvalue3d_shortdouble_llf_tf, &
                setfvalue3d_intbyte_llf_tf, &
                setfvalue3d_intshort_llf_tf, &
                setfvalue3d_intint_llf_tf, &
                setfvalue3d_intfloat_llf_tf, &
                setfvalue3d_intdouble_llf_tf, &
                setfvalue3d_floatbyte_llf_tf, &
                setfvalue3d_floatshort_llf_tf, &
                setfvalue3d_floatint_llf_tf, &
                setfvalue3d_floatfloat_llf_tf, &
                setfvalue3d_floatdouble_llf_tf, &
                setfvalue3d_doublebyte_llf_tf, &
                setfvalue3d_doubleshort_llf_tf, &
                setfvalue3d_doubleint_llf_tf, &
                setfvalue3d_doublefloat_llf_tf, &
                setfvalue3d_doubledouble_llf_tf, &
                setfvalue3d_bytebyte_lld_tf, &
                setfvalue3d_byteshort_lld_tf, &
                setfvalue3d_byteint_lld_tf, &
                setfvalue3d_bytefloat_lld_tf, &
                setfvalue3d_bytedouble_lld_tf, &
                setfvalue3d_shortbyte_lld_tf, &
                setfvalue3d_shortshort_lld_tf, &
                setfvalue3d_shortint_lld_tf, &
                setfvalue3d_shortfloat_lld_tf, &
                setfvalue3d_shortdouble_lld_tf, &
                setfvalue3d_intbyte_lld_tf, &
                setfvalue3d_intshort_lld_tf, &
                setfvalue3d_intint_lld_tf, &
                setfvalue3d_intfloat_lld_tf, &
                setfvalue3d_intdouble_lld_tf, &
                setfvalue3d_floatbyte_lld_tf, &
                setfvalue3d_floatshort_lld_tf, &
                setfvalue3d_floatint_lld_tf, &
                setfvalue3d_floatfloat_lld_tf, &
                setfvalue3d_floatdouble_lld_tf, &
                setfvalue3d_doublebyte_lld_tf, &
                setfvalue3d_doubleshort_lld_tf, &
                setfvalue3d_doubleint_lld_tf, &
                setfvalue3d_doublefloat_lld_tf, &
                setfvalue3d_doubledouble_lld_tf, &
                setfvalue3d_bytebyte_llf_td, &
                setfvalue3d_byteshort_llf_td, &
                setfvalue3d_byteint_llf_td, &
                setfvalue3d_bytefloat_llf_td, &
                setfvalue3d_bytedouble_llf_td, &
                setfvalue3d_shortbyte_llf_td, &
                setfvalue3d_shortshort_llf_td, &
                setfvalue3d_shortint_llf_td, &
                setfvalue3d_shortfloat_llf_td, &
                setfvalue3d_shortdouble_llf_td, &
                setfvalue3d_intbyte_llf_td, &
                setfvalue3d_intshort_llf_td, &
                setfvalue3d_intint_llf_td, &
                setfvalue3d_intfloat_llf_td, &
                setfvalue3d_intdouble_llf_td, &
                setfvalue3d_floatbyte_llf_td, &
                setfvalue3d_floatshort_llf_td, &
                setfvalue3d_floatint_llf_td, &
                setfvalue3d_floatfloat_llf_td, &
                setfvalue3d_floatdouble_llf_td, &
                setfvalue3d_doublebyte_llf_td, &
                setfvalue3d_doubleshort_llf_td, &
                setfvalue3d_doubleint_llf_td, &
                setfvalue3d_doublefloat_llf_td, &
                setfvalue3d_doubledouble_llf_td, &
                setfvalue3d_bytebyte_lld_td, &
                setfvalue3d_byteshort_lld_td, &
                setfvalue3d_byteint_lld_td, &
                setfvalue3d_bytefloat_lld_td, &
                setfvalue3d_bytedouble_lld_td, &
                setfvalue3d_shortbyte_lld_td, &
                setfvalue3d_shortshort_lld_td, &
                setfvalue3d_shortint_lld_td, &
                setfvalue3d_shortfloat_lld_td, &
                setfvalue3d_shortdouble_lld_td, &
                setfvalue3d_intbyte_lld_td, &
                setfvalue3d_intshort_lld_td, &
                setfvalue3d_intint_lld_td, &
                setfvalue3d_intfloat_lld_td, &
                setfvalue3d_intdouble_lld_td, &
                setfvalue3d_floatbyte_lld_td, &
                setfvalue3d_floatshort_lld_td, &
                setfvalue3d_floatint_lld_td, &
                setfvalue3d_floatfloat_lld_td, &
                setfvalue3d_floatdouble_lld_td, &
                setfvalue3d_doublebyte_lld_td, &
                setfvalue3d_doubleshort_lld_td, &
                setfvalue3d_doubleint_lld_td, &
                setfvalue3d_doublefloat_lld_td, &
                setfvalue3d_doubledouble_lld_td, &
                setfvalue4d_bytebyte_llf_ti_li, &
                setfvalue4d_shortbyte_llf_ti_li, &
                setfvalue4d_intbyte_llf_ti_li, &
                setfvalue4d_floatbyte_llf_ti_li, &
                setfvalue4d_doublebyte_llf_ti_li, &
                setfvalue4d_byteshort_llf_ti_li, &
                setfvalue4d_shortshort_llf_ti_li, &
                setfvalue4d_intshort_llf_ti_li, &
                setfvalue4d_floatshort_llf_ti_li, &
                setfvalue4d_doubleshort_llf_ti_li, &
                setfvalue4d_byteint_llf_ti_li, &
                setfvalue4d_shortint_llf_ti_li, &
                setfvalue4d_intint_llf_ti_li, &
                setfvalue4d_floatint_llf_ti_li, &
                setfvalue4d_doubleint_llf_ti_li, &
                setfvalue4d_bytefloat_llf_ti_li, &
                setfvalue4d_shortfloat_llf_ti_li, &
                setfvalue4d_intfloat_llf_ti_li, &
                setfvalue4d_floatfloat_llf_ti_li, &
                setfvalue4d_doublefloat_llf_ti_li, &
                setfvalue4d_bytedouble_llf_ti_li, &
                setfvalue4d_shortdouble_llf_ti_li, &
                setfvalue4d_intdouble_llf_ti_li, &
                setfvalue4d_floatdouble_llf_ti_li, &
                setfvalue4d_doubledouble_llf_ti_li, &
                setfvalue4d_bytebyte_lld_ti_li, &
                setfvalue4d_shortbyte_lld_ti_li, &
                setfvalue4d_intbyte_lld_ti_li, &
                setfvalue4d_floatbyte_lld_ti_li, &
                setfvalue4d_doublebyte_lld_ti_li, &
                setfvalue4d_byteshort_lld_ti_li, &
                setfvalue4d_shortshort_lld_ti_li, &
                setfvalue4d_intshort_lld_ti_li, &
                setfvalue4d_floatshort_lld_ti_li, &
                setfvalue4d_doubleshort_lld_ti_li, &
                setfvalue4d_byteint_lld_ti_li, &
                setfvalue4d_shortint_lld_ti_li, &
                setfvalue4d_intint_lld_ti_li, &
                setfvalue4d_floatint_lld_ti_li, &
                setfvalue4d_doubleint_lld_ti_li, &
                setfvalue4d_bytefloat_lld_ti_li, &
                setfvalue4d_shortfloat_lld_ti_li, &
                setfvalue4d_intfloat_lld_ti_li, &
                setfvalue4d_floatfloat_lld_ti_li, &
                setfvalue4d_doublefloat_lld_ti_li, &
                setfvalue4d_bytedouble_lld_ti_li, &
                setfvalue4d_shortdouble_lld_ti_li, &
                setfvalue4d_intdouble_lld_ti_li, &
                setfvalue4d_floatdouble_lld_ti_li, &
                setfvalue4d_doubledouble_lld_ti_li, &
                setfvalue4d_bytebyte_llf_tf_li, &
                setfvalue4d_shortbyte_llf_tf_li, &
                setfvalue4d_intbyte_llf_tf_li, &
                setfvalue4d_floatbyte_llf_tf_li, &
                setfvalue4d_doublebyte_llf_tf_li, &
                setfvalue4d_byteshort_llf_tf_li, &
                setfvalue4d_shortshort_llf_tf_li, &
                setfvalue4d_intshort_llf_tf_li, &
                setfvalue4d_floatshort_llf_tf_li, &
                setfvalue4d_doubleshort_llf_tf_li, &
                setfvalue4d_byteint_llf_tf_li, &
                setfvalue4d_shortint_llf_tf_li, &
                setfvalue4d_intint_llf_tf_li, &
                setfvalue4d_floatint_llf_tf_li, &
                setfvalue4d_doubleint_llf_tf_li, &
                setfvalue4d_bytefloat_llf_tf_li, &
                setfvalue4d_shortfloat_llf_tf_li, &
                setfvalue4d_intfloat_llf_tf_li, &
                setfvalue4d_floatfloat_llf_tf_li, &
                setfvalue4d_doublefloat_llf_tf_li, &
                setfvalue4d_bytedouble_llf_tf_li, &
                setfvalue4d_shortdouble_llf_tf_li, &
                setfvalue4d_intdouble_llf_tf_li, &
                setfvalue4d_floatdouble_llf_tf_li, &
                setfvalue4d_doubledouble_llf_tf_li, &
                setfvalue4d_bytebyte_lld_tf_li, &
                setfvalue4d_shortbyte_lld_tf_li, &
                setfvalue4d_intbyte_lld_tf_li, &
                setfvalue4d_floatbyte_lld_tf_li, &
                setfvalue4d_doublebyte_lld_tf_li, &
                setfvalue4d_byteshort_lld_tf_li, &
                setfvalue4d_shortshort_lld_tf_li, &
                setfvalue4d_intshort_lld_tf_li, &
                setfvalue4d_floatshort_lld_tf_li, &
                setfvalue4d_doubleshort_lld_tf_li, &
                setfvalue4d_byteint_lld_tf_li, &
                setfvalue4d_shortint_lld_tf_li, &
                setfvalue4d_intint_lld_tf_li, &
                setfvalue4d_floatint_lld_tf_li, &
                setfvalue4d_doubleint_lld_tf_li, &
                setfvalue4d_bytefloat_lld_tf_li, &
                setfvalue4d_shortfloat_lld_tf_li, &
                setfvalue4d_intfloat_lld_tf_li, &
                setfvalue4d_floatfloat_lld_tf_li, &
                setfvalue4d_doublefloat_lld_tf_li, &
                setfvalue4d_bytedouble_lld_tf_li, &
                setfvalue4d_shortdouble_lld_tf_li, &
                setfvalue4d_intdouble_lld_tf_li, &
                setfvalue4d_floatdouble_lld_tf_li, &
                setfvalue4d_doubledouble_lld_tf_li, &
                setfvalue4d_bytebyte_llf_td_li, &
                setfvalue4d_shortbyte_llf_td_li, &
                setfvalue4d_intbyte_llf_td_li, &
                setfvalue4d_floatbyte_llf_td_li, &
                setfvalue4d_doublebyte_llf_td_li, &
                setfvalue4d_byteshort_llf_td_li, &
                setfvalue4d_shortshort_llf_td_li, &
                setfvalue4d_intshort_llf_td_li, &
                setfvalue4d_floatshort_llf_td_li, &
                setfvalue4d_doubleshort_llf_td_li, &
                setfvalue4d_byteint_llf_td_li, &
                setfvalue4d_shortint_llf_td_li, &
                setfvalue4d_intint_llf_td_li, &
                setfvalue4d_floatint_llf_td_li, &
                setfvalue4d_doubleint_llf_td_li, &
                setfvalue4d_bytefloat_llf_td_li, &
                setfvalue4d_shortfloat_llf_td_li, &
                setfvalue4d_intfloat_llf_td_li, &
                setfvalue4d_floatfloat_llf_td_li, &
                setfvalue4d_doublefloat_llf_td_li, &
                setfvalue4d_bytedouble_llf_td_li, &
                setfvalue4d_shortdouble_llf_td_li, &
                setfvalue4d_intdouble_llf_td_li, &
                setfvalue4d_floatdouble_llf_td_li, &
                setfvalue4d_doubledouble_llf_td_li, &
                setfvalue4d_bytebyte_lld_td_li, &
                setfvalue4d_shortbyte_lld_td_li, &
                setfvalue4d_intbyte_lld_td_li, &
                setfvalue4d_floatbyte_lld_td_li, &
                setfvalue4d_doublebyte_lld_td_li, &
                setfvalue4d_byteshort_lld_td_li, &
                setfvalue4d_shortshort_lld_td_li, &
                setfvalue4d_intshort_lld_td_li, &
                setfvalue4d_floatshort_lld_td_li, &
                setfvalue4d_doubleshort_lld_td_li, &
                setfvalue4d_byteint_lld_td_li, &
                setfvalue4d_shortint_lld_td_li, &
                setfvalue4d_intint_lld_td_li, &
                setfvalue4d_floatint_lld_td_li, &
                setfvalue4d_doubleint_lld_td_li, &
                setfvalue4d_bytefloat_lld_td_li, &
                setfvalue4d_shortfloat_lld_td_li, &
                setfvalue4d_intfloat_lld_td_li, &
                setfvalue4d_floatfloat_lld_td_li, &
                setfvalue4d_doublefloat_lld_td_li, &
                setfvalue4d_bytedouble_lld_td_li, &
                setfvalue4d_shortdouble_lld_td_li, &
                setfvalue4d_intdouble_lld_td_li, &
                setfvalue4d_floatdouble_lld_td_li, &
                setfvalue4d_doubledouble_lld_td_li, &
                setfvalue4d_bytebyte_llf_ti_lf, &
                setfvalue4d_shortbyte_llf_ti_lf, &
                setfvalue4d_intbyte_llf_ti_lf, &
                setfvalue4d_floatbyte_llf_ti_lf, &
                setfvalue4d_doublebyte_llf_ti_lf, &
                setfvalue4d_byteshort_llf_ti_lf, &
                setfvalue4d_shortshort_llf_ti_lf, &
                setfvalue4d_intshort_llf_ti_lf, &
                setfvalue4d_floatshort_llf_ti_lf, &
                setfvalue4d_doubleshort_llf_ti_lf, &
                setfvalue4d_byteint_llf_ti_lf, &
                setfvalue4d_shortint_llf_ti_lf, &
                setfvalue4d_intint_llf_ti_lf, &
                setfvalue4d_floatint_llf_ti_lf, &
                setfvalue4d_doubleint_llf_ti_lf, &
                setfvalue4d_bytefloat_llf_ti_lf, &
                setfvalue4d_shortfloat_llf_ti_lf, &
                setfvalue4d_intfloat_llf_ti_lf, &
                setfvalue4d_floatfloat_llf_ti_lf, &
                setfvalue4d_doublefloat_llf_ti_lf, &
                setfvalue4d_bytedouble_llf_ti_lf, &
                setfvalue4d_shortdouble_llf_ti_lf, &
                setfvalue4d_intdouble_llf_ti_lf, &
                setfvalue4d_floatdouble_llf_ti_lf, &
                setfvalue4d_doubledouble_llf_ti_lf, &
                setfvalue4d_bytebyte_lld_ti_lf, &
                setfvalue4d_shortbyte_lld_ti_lf, &
                setfvalue4d_intbyte_lld_ti_lf, &
                setfvalue4d_floatbyte_lld_ti_lf, &
                setfvalue4d_doublebyte_lld_ti_lf, &
                setfvalue4d_byteshort_lld_ti_lf, &
                setfvalue4d_shortshort_lld_ti_lf, &
                setfvalue4d_intshort_lld_ti_lf, &
                setfvalue4d_floatshort_lld_ti_lf, &
                setfvalue4d_doubleshort_lld_ti_lf, &
                setfvalue4d_byteint_lld_ti_lf, &
                setfvalue4d_shortint_lld_ti_lf, &
                setfvalue4d_intint_lld_ti_lf, &
                setfvalue4d_floatint_lld_ti_lf, &
                setfvalue4d_doubleint_lld_ti_lf, &
                setfvalue4d_bytefloat_lld_ti_lf, &
                setfvalue4d_shortfloat_lld_ti_lf, &
                setfvalue4d_intfloat_lld_ti_lf, &
                setfvalue4d_floatfloat_lld_ti_lf, &
                setfvalue4d_doublefloat_lld_ti_lf, &
                setfvalue4d_bytedouble_lld_ti_lf, &
                setfvalue4d_shortdouble_lld_ti_lf, &
                setfvalue4d_intdouble_lld_ti_lf, &
                setfvalue4d_floatdouble_lld_ti_lf, &
                setfvalue4d_doubledouble_lld_ti_lf, &
                setfvalue4d_bytebyte_llf_tf_lf, &
                setfvalue4d_shortbyte_llf_tf_lf, &
                setfvalue4d_intbyte_llf_tf_lf, &
                setfvalue4d_floatbyte_llf_tf_lf, &
                setfvalue4d_doublebyte_llf_tf_lf, &
                setfvalue4d_byteshort_llf_tf_lf, &
                setfvalue4d_shortshort_llf_tf_lf, &
                setfvalue4d_intshort_llf_tf_lf, &
                setfvalue4d_floatshort_llf_tf_lf, &
                setfvalue4d_doubleshort_llf_tf_lf, &
                setfvalue4d_byteint_llf_tf_lf, &
                setfvalue4d_shortint_llf_tf_lf, &
                setfvalue4d_intint_llf_tf_lf, &
                setfvalue4d_floatint_llf_tf_lf, &
                setfvalue4d_doubleint_llf_tf_lf, &
                setfvalue4d_bytefloat_llf_tf_lf, &
                setfvalue4d_shortfloat_llf_tf_lf, &
                setfvalue4d_intfloat_llf_tf_lf, &
                setfvalue4d_floatfloat_llf_tf_lf, &
                setfvalue4d_doublefloat_llf_tf_lf, &
                setfvalue4d_bytedouble_llf_tf_lf, &
                setfvalue4d_shortdouble_llf_tf_lf, &
                setfvalue4d_intdouble_llf_tf_lf, &
                setfvalue4d_floatdouble_llf_tf_lf, &
                setfvalue4d_doubledouble_llf_tf_lf, &
                setfvalue4d_bytebyte_lld_tf_lf, &
                setfvalue4d_shortbyte_lld_tf_lf, &
                setfvalue4d_intbyte_lld_tf_lf, &
                setfvalue4d_floatbyte_lld_tf_lf, &
                setfvalue4d_doublebyte_lld_tf_lf, &
                setfvalue4d_byteshort_lld_tf_lf, &
                setfvalue4d_shortshort_lld_tf_lf, &
                setfvalue4d_intshort_lld_tf_lf, &
                setfvalue4d_floatshort_lld_tf_lf, &
                setfvalue4d_doubleshort_lld_tf_lf, &
                setfvalue4d_byteint_lld_tf_lf, &
                setfvalue4d_shortint_lld_tf_lf, &
                setfvalue4d_intint_lld_tf_lf, &
                setfvalue4d_floatint_lld_tf_lf, &
                setfvalue4d_doubleint_lld_tf_lf, &
                setfvalue4d_bytefloat_lld_tf_lf, &
                setfvalue4d_shortfloat_lld_tf_lf, &
                setfvalue4d_intfloat_lld_tf_lf, &
                setfvalue4d_floatfloat_lld_tf_lf, &
                setfvalue4d_doublefloat_lld_tf_lf, &
                setfvalue4d_bytedouble_lld_tf_lf, &
                setfvalue4d_shortdouble_lld_tf_lf, &
                setfvalue4d_intdouble_lld_tf_lf, &
                setfvalue4d_floatdouble_lld_tf_lf, &
                setfvalue4d_doubledouble_lld_tf_lf, &
                setfvalue4d_bytebyte_llf_td_lf, &
                setfvalue4d_shortbyte_llf_td_lf, &
                setfvalue4d_intbyte_llf_td_lf, &
                setfvalue4d_floatbyte_llf_td_lf, &
                setfvalue4d_doublebyte_llf_td_lf, &
                setfvalue4d_byteshort_llf_td_lf, &
                setfvalue4d_shortshort_llf_td_lf, &
                setfvalue4d_intshort_llf_td_lf, &
                setfvalue4d_floatshort_llf_td_lf, &
                setfvalue4d_doubleshort_llf_td_lf, &
                setfvalue4d_byteint_llf_td_lf, &
                setfvalue4d_shortint_llf_td_lf, &
                setfvalue4d_intint_llf_td_lf, &
                setfvalue4d_floatint_llf_td_lf, &
                setfvalue4d_doubleint_llf_td_lf, &
                setfvalue4d_bytefloat_llf_td_lf, &
                setfvalue4d_shortfloat_llf_td_lf, &
                setfvalue4d_intfloat_llf_td_lf, &
                setfvalue4d_floatfloat_llf_td_lf, &
                setfvalue4d_doublefloat_llf_td_lf, &
                setfvalue4d_bytedouble_llf_td_lf, &
                setfvalue4d_shortdouble_llf_td_lf, &
                setfvalue4d_intdouble_llf_td_lf, &
                setfvalue4d_floatdouble_llf_td_lf, &
                setfvalue4d_doubledouble_llf_td_lf, &
                setfvalue4d_bytebyte_lld_td_lf, &
                setfvalue4d_shortbyte_lld_td_lf, &
                setfvalue4d_intbyte_lld_td_lf, &
                setfvalue4d_floatbyte_lld_td_lf, &
                setfvalue4d_doublebyte_lld_td_lf, &
                setfvalue4d_byteshort_lld_td_lf, &
                setfvalue4d_shortshort_lld_td_lf, &
                setfvalue4d_intshort_lld_td_lf, &
                setfvalue4d_floatshort_lld_td_lf, &
                setfvalue4d_doubleshort_lld_td_lf, &
                setfvalue4d_byteint_lld_td_lf, &
                setfvalue4d_shortint_lld_td_lf, &
                setfvalue4d_intint_lld_td_lf, &
                setfvalue4d_floatint_lld_td_lf, &
                setfvalue4d_doubleint_lld_td_lf, &
                setfvalue4d_bytefloat_lld_td_lf, &
                setfvalue4d_shortfloat_lld_td_lf, &
                setfvalue4d_intfloat_lld_td_lf, &
                setfvalue4d_floatfloat_lld_td_lf, &
                setfvalue4d_doublefloat_lld_td_lf, &
                setfvalue4d_bytedouble_lld_td_lf, &
                setfvalue4d_shortdouble_lld_td_lf, &
                setfvalue4d_intdouble_lld_td_lf, &
                setfvalue4d_floatdouble_lld_td_lf, &
                setfvalue4d_doubledouble_lld_td_lf
end interface setFillValue

interface gengrid
  module procedure gengrid2d_byte_llf, &
                gengrid2d_short_llf, &
                gengrid2d_int_llf, &
                gengrid2d_float_llf, &
                gengrid2d_double_llf, &
                gengrid2d_byte_lld, &
                gengrid2d_short_lld, &
                gengrid2d_int_lld, &
                gengrid2d_float_lld, &
                gengrid2d_double_lld, &
                gengrid3d_byte_llf_ti, &
                gengrid3d_short_llf_ti, &
                gengrid3d_int_llf_ti, &
                gengrid3d_float_llf_ti, &
                gengrid3d_double_llf_ti, &
                gengrid3d_byte_lld_ti, &
                gengrid3d_short_lld_ti, &
                gengrid3d_int_lld_ti, &
                gengrid3d_float_lld_ti, &
                gengrid3d_double_lld_ti, &
                gengrid3d_byte_llf_tf, &
                gengrid3d_short_llf_tf, &
                gengrid3d_int_llf_tf, &
                gengrid3d_float_llf_tf, &
                gengrid3d_double_llf_tf, &
                gengrid3d_byte_lld_tf, &
                gengrid3d_short_lld_tf, &
                gengrid3d_int_lld_tf, &
                gengrid3d_float_lld_tf, &
                gengrid3d_double_lld_tf, &
                gengrid3d_byte_llf_td, &
                gengrid3d_short_llf_td, &
                gengrid3d_int_llf_td, &
                gengrid3d_float_llf_td, &
                gengrid3d_double_llf_td, &
                gengrid3d_byte_lld_td, &
                gengrid3d_short_lld_td, &
                gengrid3d_int_lld_td, &
                gengrid3d_float_lld_td, &
                gengrid3d_double_lld_td, &
                gengrid4d_byte_llf_ti_li, &
                gengrid4d_short_llf_ti_li, &
                gengrid4d_int_llf_ti_li, &
                gengrid4d_float_llf_ti_li, &
                gengrid4d_double_llf_ti_li, &
                gengrid4d_byte_lld_ti_li, &
                gengrid4d_short_lld_ti_li, &
                gengrid4d_int_lld_ti_li, &
                gengrid4d_float_lld_ti_li, &
                gengrid4d_double_lld_ti_li, &
                gengrid4d_byte_llf_tf_li, &
                gengrid4d_short_llf_tf_li, &
                gengrid4d_int_llf_tf_li, &
                gengrid4d_float_llf_tf_li, &
                gengrid4d_double_llf_tf_li, &
                gengrid4d_byte_lld_tf_li, &
                gengrid4d_short_lld_tf_li, &
                gengrid4d_int_lld_tf_li, &
                gengrid4d_float_lld_tf_li, &
                gengrid4d_double_lld_tf_li, &
                gengrid4d_byte_llf_td_li, &
                gengrid4d_short_llf_td_li, &
                gengrid4d_int_llf_td_li, &
                gengrid4d_float_llf_td_li, &
                gengrid4d_double_llf_td_li, &
                gengrid4d_byte_lld_td_li, &
                gengrid4d_short_lld_td_li, &
                gengrid4d_int_lld_td_li, &
                gengrid4d_float_lld_td_li, &
                gengrid4d_double_lld_td_li, &
                gengrid4d_byte_llf_ti_lf, &
                gengrid4d_short_llf_ti_lf, &
                gengrid4d_int_llf_ti_lf, &
                gengrid4d_float_llf_ti_lf, &
                gengrid4d_double_llf_ti_lf, &
                gengrid4d_byte_lld_ti_lf, &
                gengrid4d_short_lld_ti_lf, &
                gengrid4d_int_lld_ti_lf, &
                gengrid4d_float_lld_ti_lf, &
                gengrid4d_double_lld_ti_lf, &
                gengrid4d_byte_llf_tf_lf, &
                gengrid4d_short_llf_tf_lf, &
                gengrid4d_int_llf_tf_lf, &
                gengrid4d_float_llf_tf_lf, &
                gengrid4d_double_llf_tf_lf, &
                gengrid4d_byte_lld_tf_lf, &
                gengrid4d_short_lld_tf_lf, &
                gengrid4d_int_lld_tf_lf, &
                gengrid4d_float_lld_tf_lf, &
                gengrid4d_double_lld_tf_lf, &
                gengrid4d_byte_llf_td_lf, &
                gengrid4d_short_llf_td_lf, &
                gengrid4d_int_llf_td_lf, &
                gengrid4d_float_llf_td_lf, &
                gengrid4d_double_llf_td_lf, &
                gengrid4d_byte_lld_td_lf, &
                gengrid4d_short_lld_td_lf, &
                gengrid4d_int_lld_td_lf, &
                gengrid4d_float_lld_td_lf, &
                gengrid4d_double_lld_td_lf
end interface gengrid

interface dealloc
  module procedure dealloc2d_byte_llf, &
                dealloc2d_short_llf, &
                dealloc2d_int_llf, &
                dealloc2d_float_llf, &
                dealloc2d_double_llf, &
                dealloc2d_byte_lld, &
                dealloc2d_short_lld, &
                dealloc2d_int_lld, &
                dealloc2d_float_lld, &
                dealloc2d_double_lld, &
                dealloc3d_byte_llf_ti, &
                dealloc3d_short_llf_ti, &
                dealloc3d_int_llf_ti, &
                dealloc3d_float_llf_ti, &
                dealloc3d_double_llf_ti, &
                dealloc3d_byte_lld_ti, &
                dealloc3d_short_lld_ti, &
                dealloc3d_int_lld_ti, &
                dealloc3d_float_lld_ti, &
                dealloc3d_double_lld_ti, &
                dealloc3d_byte_llf_tf, &
                dealloc3d_short_llf_tf, &
                dealloc3d_int_llf_tf, &
                dealloc3d_float_llf_tf, &
                dealloc3d_double_llf_tf, &
                dealloc3d_byte_lld_tf, &
                dealloc3d_short_lld_tf, &
                dealloc3d_int_lld_tf, &
                dealloc3d_float_lld_tf, &
                dealloc3d_double_lld_tf, &
                dealloc3d_byte_llf_td, &
                dealloc3d_short_llf_td, &
                dealloc3d_int_llf_td, &
                dealloc3d_float_llf_td, &
                dealloc3d_double_llf_td, &
                dealloc3d_byte_lld_td, &
                dealloc3d_short_lld_td, &
                dealloc3d_int_lld_td, &
                dealloc3d_float_lld_td, &
                dealloc3d_double_lld_td, &
                dealloc4d_byte_llf_ti_li, &
                dealloc4d_short_llf_ti_li, &
                dealloc4d_int_llf_ti_li, &
                dealloc4d_float_llf_ti_li, &
                dealloc4d_double_llf_ti_li, &
                dealloc4d_byte_lld_ti_li, &
                dealloc4d_short_lld_ti_li, &
                dealloc4d_int_lld_ti_li, &
                dealloc4d_float_lld_ti_li, &
                dealloc4d_double_lld_ti_li, &
                dealloc4d_byte_llf_tf_li, &
                dealloc4d_short_llf_tf_li, &
                dealloc4d_int_llf_tf_li, &
                dealloc4d_float_llf_tf_li, &
                dealloc4d_double_llf_tf_li, &
                dealloc4d_byte_lld_tf_li, &
                dealloc4d_short_lld_tf_li, &
                dealloc4d_int_lld_tf_li, &
                dealloc4d_float_lld_tf_li, &
                dealloc4d_double_lld_tf_li, &
                dealloc4d_byte_llf_td_li, &
                dealloc4d_short_llf_td_li, &
                dealloc4d_int_llf_td_li, &
                dealloc4d_float_llf_td_li, &
                dealloc4d_double_llf_td_li, &
                dealloc4d_byte_lld_td_li, &
                dealloc4d_short_lld_td_li, &
                dealloc4d_int_lld_td_li, &
                dealloc4d_float_lld_td_li, &
                dealloc4d_double_lld_td_li, &
                dealloc4d_byte_llf_ti_lf, &
                dealloc4d_short_llf_ti_lf, &
                dealloc4d_int_llf_ti_lf, &
                dealloc4d_float_llf_ti_lf, &
                dealloc4d_double_llf_ti_lf, &
                dealloc4d_byte_lld_ti_lf, &
                dealloc4d_short_lld_ti_lf, &
                dealloc4d_int_lld_ti_lf, &
                dealloc4d_float_lld_ti_lf, &
                dealloc4d_double_lld_ti_lf, &
                dealloc4d_byte_llf_tf_lf, &
                dealloc4d_short_llf_tf_lf, &
                dealloc4d_int_llf_tf_lf, &
                dealloc4d_float_llf_tf_lf, &
                dealloc4d_double_llf_tf_lf, &
                dealloc4d_byte_lld_tf_lf, &
                dealloc4d_short_lld_tf_lf, &
                dealloc4d_int_lld_tf_lf, &
                dealloc4d_float_lld_tf_lf, &
                dealloc4d_double_lld_tf_lf, &
                dealloc4d_byte_llf_td_lf, &
                dealloc4d_short_llf_td_lf, &
                dealloc4d_int_llf_td_lf, &
                dealloc4d_float_llf_td_lf, &
                dealloc4d_double_llf_td_lf, &
                dealloc4d_byte_lld_td_lf, &
                dealloc4d_short_lld_td_lf, &
                dealloc4d_int_lld_td_lf, &
                dealloc4d_float_lld_td_lf, &
                dealloc4d_double_lld_td_lf
end interface dealloc
